# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositiveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 12, 14, 20, 59, 21, 911738))),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='positivelog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Room'),
        ),
    ]
