# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stateFlag',
            fields=[
                ('state', models.BooleanField(default=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='positivelog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='positivelog',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
