# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20161217_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateflag',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
