# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20161217_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('userType', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='stateflag',
            name='name',
            field=models.CharField(default='alertState', max_length=100, primary_key=True, serialize=False),
        ),
    ]
